# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Awebone's Blog
subtitle: 见多方能识广，进而才可以融会贯通；取他人之所长，谦而才可以为我所用。
description: Python开发，大数据开发，算法研究者
author: Awebone
language: zh-CN
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://www.awebone.com
#url: https://awebone.gitee.io/
#url: https://xuyanbo03.github.io/
root: /
permalink: posts/:abbrlink/
#permalink: :year/:month/:title/
#permalink: :year/:month/:day/:title/
permalink_defaults:

# abbrlink config
abbrlink:
  alg: crc32  #support crc16(default) and crc32
  rep: hex    #support dec(default) and hex

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

archive_generator:
  per_page: 0
  yearly: false
  monthly: false
  daily: false

category_generator:
  per_page: 0

tag_generator:
  per_page: 0


# Extensions
Plugins: 
  - hexo-generator-sitemap
  - hexo-generator-baidu-sitemap
  
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next-new

# all_minifier: true
# html_minifier:
#   enable: true
#   ignore_error: false
#   exclude:

# css_minifier:
#   enable: true
#   exclude:
#     - '*.min.css'

# js_minifier:
#   enable: true
#   mangle: true
#   output:
#   compress:
#   exclude:
#     - '*.min.js'

# js_concator:
#   enable: false
#   bundle_path: '/js/bundle.js'
#   front: false
#   silent: false

# image_minifier:
#   enable: true
#   interlaced: false
#   multipass: false
#   optimizationLevel: 2
#   pngquant: false
#   progressive: false

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
-  type: git
   repository: git@ali-beijing:/home/git/blog.git
   branch: master
-  type: git
   repository: https://gitee.com/awebone/awebone.git
   branch: master
-  type: git
   repository: https://github.com/xuyanbo03/xuyanbo03.github.io.git
   branch: blog

admin:
  deployCommand: 'hexo-publish.bat'


  
#duoshuo_shortname: 
#duoshuo_share: false

#search: b2756236edba983e404290b5b4717f8d
search: 
  path: search.xml
  field: post
  format: html
  limit: 10000

#algolia:
#appId: 'OBNY7K0AIA'
#3apiKey: '3525bc24fec5733d9bae4ad70f1687fc'
#adminApiKey: 'd98e44e3a440ced1300b466cb9e045e1'
#indexName: 'xuyanbo03'
#chunkSize: 5000
#fields:
#- title
#- slug
#- path
#- content:strip

#leancloud_visitors:
#  enable: false
#  app_id: QJPFDCSOCoSkkmOd9nn6sW7J-gzGzoHsz
#  app_key: lf47PD0nKXMeiiHaxRbtdY8r

plugins: hexo-generator-feed

feed:
  type: atom
  path: atom.xml
  limit: 0
  hub:
  content: true


githubEmojis:
  enable: true
  idName: github-emoji
  unicode: false
  styles:
  localEmojis:


# offline config passed to sw-precache.
service_worker:
  maximumFileSizeToCacheInBytes: 5242880
  staticFileGlobs:
  - public/**/*.{js,html,css,png,jpg,gif,svg,eot,ttf,woff,woff2}
  stripPrefix: public
  verbose: true


# https://github.com/lavas-project/hexo-pwa
pwa:
  manifest:
    path: /manifest.json
    body:
      name: Awebone
      short_name: Awebone
      description: Awebone's Blog
      icons:
      - src: /images/icons/icon-72x72.png
        sizes: 72x72
        type: image/png
      - src: /images/icons/icon-152x152.png
        sizes: 152x152
        type: image/png
      start_url: /index.html
      theme_color: '#2196f3'
      background_color: '#2196f3'
      display: standalone
  serviceWorker:
    path: /sw.js
    preload:
      urls:
      - /
      posts: 5
    opts:
      networkTimeoutSeconds: 5
    routes:
    - pattern: !!js/regexp /hm.baidu.com/
      strategy: networkOnly
    - pattern: !!js/regexp /.*\.(js|css|jpg|jpeg|png|gif)$/
      strategy: cacheFirst
    - pattern: !!js/regexp /\//
      strategy: networkFirst
  priority: 5


links_title: 友链
links:
    Segmentfault: https://segmentfault.com/ || spinner
    Github: https://github.com/ || github
    码云: https://gitee.com || heartbeat

# sitemap
sitemap:
  path: sitemap.xml
baidusitemap:
  path: baidusitemap.xml